name: Build EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install keyboard requests psutil pyinstaller
    
    - name: Build EXE
      run: |
        pyinstaller --onefile --noconsole --name LUBV_Injector ValornatCheat.py
    
    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: LUBV_Injector
        path: dist/LUBV_Injector.exe
